home/urls.py
from django.conf.urls import url

from . import views
app_name = 'home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

store/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from datetime import datetime
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class UnderCategory(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True )
    def __str__(self):
        return self.title


class Product(models.Model):
    ucategory = models.ForeignKey(UnderCategory, on_delete=models.CASCADE, blank=True, null=True )
    name = models.CharField(max_length=200)
    price = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.name

home/views.py
# Create your views here.
from django.utils import timezone
from django.views import generic
from .models import Category, Product


class IndexView(generic.ListView):
    template_name = 'home.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Category.objects.all()


class DetailView(generic.DetailView):
    template_name = 'product.html'
    model = Category

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Category.objects.all()

home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
    <link type="text/css" rel="stylesheet" href="/static/css/bootstrap.min.css"/>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center">
                    <h1>Каегорії товару</h1>
                </div>
            </div>
        </div>
        <section>
            <div class="row">
            <div class="col-md-12">
                    {% for category in category_list %}

                        <div class="col-md-3 text-center">
                            <a href="{% url  'home:detail' category.id %}">{{ category.title }}</a>
                        </div>

                    {% endfor %}

            </div>
         </div>
        </section>
    </div>
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

home/templates/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Продукти категорії</title>
</head>
<body>
<h1> Продукти категорії {{ category.title }}</h1>
{% for product in category.product_set.all %}
    {{ product.name_product }}
    <hr>
    <br>
{% endfor %}

</body>
</html>